/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesAiTransformationAutomationRouteImport } from './routes/services.ai-transformation-automation'
import { Route as ServicesCloudInfrastructureModernizationRouteImport } from './routes/services.cloud-infrastructure-modernization'
import { Route as ServicesCybersecurityBusinessResilienceRouteImport } from './routes/services.cybersecurity-business-resilience'
import { Route as ServicesItStrategyDigitalTransformationRouteImport } from './routes/services.it-strategy-digital-transformation'
import { Route as ServicesManagedItOperationsRouteImport } from './routes/services.managed-it-operations'
import { Route as ServicesTechnologyTalentProfessionalServicesRouteImport } from './routes/services.technology-talent-professional-services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiTransformationAutomationRoute =
  ServicesAiTransformationAutomationRouteImport.update({
    id: '/ai-transformation-automation',
    path: '/ai-transformation-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCloudInfrastructureModernizationRoute =
  ServicesCloudInfrastructureModernizationRouteImport.update({
    id: '/cloud-infrastructure-modernization',
    path: '/cloud-infrastructure-modernization',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCybersecurityBusinessResilienceRoute =
  ServicesCybersecurityBusinessResilienceRouteImport.update({
    id: '/cybersecurity-business-resilience',
    path: '/cybersecurity-business-resilience',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesItStrategyDigitalTransformationRoute =
  ServicesItStrategyDigitalTransformationRouteImport.update({
    id: '/it-strategy-digital-transformation',
    path: '/it-strategy-digital-transformation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesManagedItOperationsRoute =
  ServicesManagedItOperationsRouteImport.update({
    id: '/managed-it-operations',
    path: '/managed-it-operations',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTechnologyTalentProfessionalServicesRoute =
  ServicesTechnologyTalentProfessionalServicesRouteImport.update({
    id: '/technology-talent-professional-services',
    path: '/technology-talent-professional-services',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ai-transformation-automation': typeof ServicesAiTransformationAutomationRoute
  '/services/cloud-infrastructure-modernization': typeof ServicesCloudInfrastructureModernizationRoute
  '/services/cybersecurity-business-resilience': typeof ServicesCybersecurityBusinessResilienceRoute
  '/services/it-strategy-digital-transformation': typeof ServicesItStrategyDigitalTransformationRoute
  '/services/managed-it-operations': typeof ServicesManagedItOperationsRoute
  '/services/technology-talent-professional-services': typeof ServicesTechnologyTalentProfessionalServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ai-transformation-automation': typeof ServicesAiTransformationAutomationRoute
  '/services/cloud-infrastructure-modernization': typeof ServicesCloudInfrastructureModernizationRoute
  '/services/cybersecurity-business-resilience': typeof ServicesCybersecurityBusinessResilienceRoute
  '/services/it-strategy-digital-transformation': typeof ServicesItStrategyDigitalTransformationRoute
  '/services/managed-it-operations': typeof ServicesManagedItOperationsRoute
  '/services/technology-talent-professional-services': typeof ServicesTechnologyTalentProfessionalServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ai-transformation-automation': typeof ServicesAiTransformationAutomationRoute
  '/services/cloud-infrastructure-modernization': typeof ServicesCloudInfrastructureModernizationRoute
  '/services/cybersecurity-business-resilience': typeof ServicesCybersecurityBusinessResilienceRoute
  '/services/it-strategy-digital-transformation': typeof ServicesItStrategyDigitalTransformationRoute
  '/services/managed-it-operations': typeof ServicesManagedItOperationsRoute
  '/services/technology-talent-professional-services': typeof ServicesTechnologyTalentProfessionalServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/resources'
    | '/services'
    | '/services/ai-transformation-automation'
    | '/services/cloud-infrastructure-modernization'
    | '/services/cybersecurity-business-resilience'
    | '/services/it-strategy-digital-transformation'
    | '/services/managed-it-operations'
    | '/services/technology-talent-professional-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/resources'
    | '/services'
    | '/services/ai-transformation-automation'
    | '/services/cloud-infrastructure-modernization'
    | '/services/cybersecurity-business-resilience'
    | '/services/it-strategy-digital-transformation'
    | '/services/managed-it-operations'
    | '/services/technology-talent-professional-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/learn'
    | '/resources'
    | '/services'
    | '/services/ai-transformation-automation'
    | '/services/cloud-infrastructure-modernization'
    | '/services/cybersecurity-business-resilience'
    | '/services/it-strategy-digital-transformation'
    | '/services/managed-it-operations'
    | '/services/technology-talent-professional-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LearnRoute: typeof LearnRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-transformation-automation': {
      id: '/services/ai-transformation-automation'
      path: '/ai-transformation-automation'
      fullPath: '/services/ai-transformation-automation'
      preLoaderRoute: typeof ServicesAiTransformationAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-infrastructure-modernization': {
      id: '/services/cloud-infrastructure-modernization'
      path: '/cloud-infrastructure-modernization'
      fullPath: '/services/cloud-infrastructure-modernization'
      preLoaderRoute: typeof ServicesCloudInfrastructureModernizationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cybersecurity-business-resilience': {
      id: '/services/cybersecurity-business-resilience'
      path: '/cybersecurity-business-resilience'
      fullPath: '/services/cybersecurity-business-resilience'
      preLoaderRoute: typeof ServicesCybersecurityBusinessResilienceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/it-strategy-digital-transformation': {
      id: '/services/it-strategy-digital-transformation'
      path: '/it-strategy-digital-transformation'
      fullPath: '/services/it-strategy-digital-transformation'
      preLoaderRoute: typeof ServicesItStrategyDigitalTransformationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/managed-it-operations': {
      id: '/services/managed-it-operations'
      path: '/managed-it-operations'
      fullPath: '/services/managed-it-operations'
      preLoaderRoute: typeof ServicesManagedItOperationsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technology-talent-professional-services': {
      id: '/services/technology-talent-professional-services'
      path: '/technology-talent-professional-services'
      fullPath: '/services/technology-talent-professional-services'
      preLoaderRoute: typeof ServicesTechnologyTalentProfessionalServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiTransformationAutomationRoute: typeof ServicesAiTransformationAutomationRoute
  ServicesCloudInfrastructureModernizationRoute: typeof ServicesCloudInfrastructureModernizationRoute
  ServicesCybersecurityBusinessResilienceRoute: typeof ServicesCybersecurityBusinessResilienceRoute
  ServicesItStrategyDigitalTransformationRoute: typeof ServicesItStrategyDigitalTransformationRoute
  ServicesManagedItOperationsRoute: typeof ServicesManagedItOperationsRoute
  ServicesTechnologyTalentProfessionalServicesRoute: typeof ServicesTechnologyTalentProfessionalServicesRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiTransformationAutomationRoute:
    ServicesAiTransformationAutomationRoute,
  ServicesCloudInfrastructureModernizationRoute:
    ServicesCloudInfrastructureModernizationRoute,
  ServicesCybersecurityBusinessResilienceRoute:
    ServicesCybersecurityBusinessResilienceRoute,
  ServicesItStrategyDigitalTransformationRoute:
    ServicesItStrategyDigitalTransformationRoute,
  ServicesManagedItOperationsRoute: ServicesManagedItOperationsRoute,
  ServicesTechnologyTalentProfessionalServicesRoute:
    ServicesTechnologyTalentProfessionalServicesRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LearnRoute: LearnRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
